// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywmluqqqtgzzmzwtvuuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bWx1cXFxdGd6em16d3R2dXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDQ2ODUsImV4cCI6MjA3ODI4MDY4NX0.1A3kI9k6qkZjR8_ciLv-B-9RNsTbT44VNxzjSCMNQQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});